[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[font]
size = 14

[font.normal]
family = "MesloLGS Nerd Font Mono"

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true

[window]
startup_mode = "Maximized"
decorations = "Buttonless"
padding = { x = 10, y = 10 }
dynamic_padding = true

[keyboard]
bindings = [
  { key = "Left", mods = "Alt", chars = "\u001bB" },
  { key = "Right", mods = "Alt", chars = "\u001bF" },
  { key = "Left", mods = "Command", chars = "\u001bOH" },
  { key = "Right", mods = "Command", chars = "\u001bOF" },
  { key = "Back", mods = "Command", chars = "\u0015" },
  { key = "L", mods = "Command", command = { program = "/opt/homebrew/bin/tmux", args = [
    "display-popup",
    "-E",
    "-h 95%",
    "-w 95%",
    "source ~/.config/zsh/work.zsh && lazygit",
  ] } },
  { key = "Y", mods = "Command", command = { program = "/opt/homebrew/bin/tmux", args = [
    "display-popup",
    "-E",
    "source ~/.config/zsh/work.zsh && node $HOME/Work/yacht/dist/index.js",
  ] } },
  { key = "G", mods = "Command", command = { program = "/opt/homebrew/bin/tmux", args = [
    "display-popup",
    "-E",
    "tt",
  ] } },
  { key = "G", mods = "Command|Alt", command = { program = "/opt/homebrew/bin/tmux", args = [
    "display-popup",
    "-E",
    "tmux-switcher",
  ] } },
  { key = "G", mods = "Command|Shift", command = { program = "/opt/homebrew/bin/tmux", args = [
    "switch-client",
    "-l",
  ] } },
  { key = "W", mods = "Command", command = { program = "/opt/homebrew/bin/tmux", args = [
    "kill-window",
  ] } },
  { key = "W", mods = "Command|Shift", command = { program = "/opt/homebrew/bin/tmux", args = [
    "kill-session",
  ] } },
]
