# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
quitOnTopLevelReturn: true
git:
  pagers:
    - pager: delta --dark --paging=never
gui:
  switchTabsWithPanelJumpKeys: true
